import { EventEmitter, Injectable } from '@angular/core';

import { Locale } from '../interfaces/Locale';

export interface LocaleEmitterValue {
  newLocale: Locale, prevLocale: Locale
}

@Injectable({ providedIn: 'root' })
export class LocalizationService {

  localeEmitter: EventEmitter<LocaleEmitterValue> = new EventEmitter<LocaleEmitterValue>();

  locale: Locale = 'en';

  constructor() { }

  drawerItems = {
    'en': {
      team: 'Team',
      dashboard: 'Dashboard',
      planning: 'Planning',
      profile: 'Profile',
      info: 'Info'
    },
    'de': {
      team: 'Team',
      dashboard: 'Dashboard',
      planning: 'Planung',
      profile: 'Profil',
      info: 'Info'
    },
    'fr': {
      team: 'Équipe',
      dashboard: 'Tableau de bord',
      planning: 'Planification',
      profile: 'Profil',
      info: 'Info'
    },
    'es': {
      team: 'Equipo',
      dashboard: 'Tablero',
      planning: 'Planificación',
      profile: 'Perfil',
      info: 'Información'
    }
  }

  projectName = {
    en: 'Smart Project',
    de: 'Intelligentes Projekt',
    fr: 'Projet intelligent',
    es: 'Proyecto inteligente'
  }

  languageString = {
    en: 'Language',
    de: 'Sprache',
    fr: 'Langue',
    es: 'Idioma'
  }

  teamMembers = {
    en: 'Team Members',
    de: 'Teammitglieder',
    fr: "Membres de l'équipe",
    es: 'Miembros del equipo'
  }

  myTeamStrings = {
    en: 'My Team',
    de: 'Mein Team',
    fr: 'Mon équipe',
    es: 'Mi equipo'
  }

  allTeamsStrings = {
    en: 'All Teams',
    de: 'Alle Teams',
    fr: 'Toutes les équipes',
    es: 'Todos los equipos'
  }

  gridColumnLabels = {
    en: ['Full Name', 'Country', 'Job Title', 'Department', 'Hire Date', 'Phone', 'Address', 'City'],
    de: ['Vollständiger Name', 'Land', 'Berufsbezeichnung', 'Abteilung', 'Einstellungsdatum', 'Telefon', 'Adresse', 'Stadt'],
    fr: ["Nom complet", "Pays", "Titre du poste", "Département", "Date d'embauche", "Téléphone", "Adresse", "Ville"],
    es: ['Nombre completo', 'País', 'Puesto de trabajo', 'Departamento', 'Fecha de contratación', 'Teléfono', 'Dirección', 'Ciudad']
  };

  gridColumnGroupLabels = {
    en: ['Employee', 'Job information', 'Contacts'],
    de: ['Mitarbeiter', 'Jobinformationen', 'Kontakte'],
    fr: ['Employé', 'Informations sur l\'emploi', 'Contacts'],
    es: ['Empleado', 'Información laboral', 'Contactos']
  };

  updateLocale(locale: Locale = 'en') {
    const prevLocale = this.locale;

    if (this.isLocale(locale)) {
      this.locale = locale;
      this.localeEmitter.emit({ newLocale: locale, prevLocale });
    } else {
      this.locale = 'en';
      this.localeEmitter.emit({ newLocale: 'en', prevLocale })
    }
  }

  getDrawerItemName(selectedItem: 'team' | 'dashboard' | 'planning' | 'profile' | 'info', locale?: Locale) { return this.drawerItems[locale || this.locale][selectedItem] }

  getDrawerItemsNames(locale?: Locale): {
    team: string;
    dashboard: string;
    planning: string;
    profile: string;
    info: string;
  } {
    return this.drawerItems[locale || this.locale];
  }

  getProjectName(locale?: Locale) { return this.projectName[locale || this.locale] }

  getLanguage(locale?: Locale) { return this.languageString[locale || this.locale] }

  getTeamMembersString(locale?: Locale) { return this.teamMembers[locale || this.locale] }

  getMyTeamString(locale?: Locale) { return this.myTeamStrings[locale || this.locale] }

  getAllTeamsString(locale?: Locale) { return this.allTeamsStrings[locale || this.locale] }

  isLocale(value: string): value is Locale {
    return ['en', 'de', 'fr', 'es'].includes(value);
  }

  getGridSearchInColumnsString(locale?: Locale) {
    switch (locale || this.locale) {
      case 'en':
        return "Search in columns";
      case 'de':
        return "Suche in Spalten";
      case 'fr':
        return "Rechercher dans les colonnes";
      case 'es':
        return "Buscar en las columnas";
    }
  }

  getGridExportToString(exportTo: string, locale?: Locale) {
    const exportToStrings = {
      en: {
        xlsx: 'Export to Excel',
        pdf: 'Export to PDF'
      },
      de: {
        xlsx: 'In Excel exportieren',
        pdf: 'In PDF exportieren'
      },
      fr: {
        xlsx: 'Exporter vers Excel',
        pdf: 'Exporter vers PDF'
      },
      es: {
        xlsx: 'Exportar a Excel',
        pdf: 'Exportar a PDF'
      }
    };

    if (exportTo === 'xlsx' || exportTo === 'pdf') {
      return exportToStrings[locale || this.locale][exportTo]
    }

    return ''
  }

  getGridMessages() {
    const gridMessages = {
      "en": {
        "invalidColumnProperty": "{{elementType}}: Invalid property name \"{{propertyName}}\" set for Column: \"{{type}}\"",
        "invalidRowProperty": "{{elementType}}: Invalid property name \"{{propertyName}}\" set for Row\"",
        "invalidCellValue": "Invalid cell value \"{{value}}\", Validation rule: \"{{validationRule}}\"",
        "frozenColumns": "{{elementType}}: To Pin/Freeze a column group, all columns within it should be frozen.",
        "frozenRows": "{{elementType}}: To Pin/Freeze a special cell, all rows within it should be frozen.",
        "columnGroups": "{{elementType}}: Please, check the initialization of the smartGrid's columns array. The columns in a column group are expected to be siblings in the columns array.",
        "min": "Min: {{value}}",
        "max": "Max: {{value}} ",
        "sum": "Sum: {{value}} ",
        "avg": "Avg: {{value}} ",
        "count": "Count: {{value}} ",
        "pagerFirstButton": "First",
        "pagerLastButton": "Last",
        "pagerPreviousButton": "Previous",
        "pagerNextButton": "Next",
        "pagerNavigateToLabel": "Go to:",
        "pagerPageSizeLabel": "Show:",
        "pagerNavigateToInputPlaceholder": "",
        "pagerEllipsis": "...",
        "pagerSummaryString": "of",
        "pagerSummaryPrefix": "of",
        "pagerSummarySuffix": "",
        "columnMenuCustomizeType": "Customize type",
        "columnMenuItemRename": "Rename",
        "columnMenuItemEditDescription": "Edit description",
        "columnMenuItemDuplicate": "Duplicate",
        "columnMenuItemInsertLeft": "Insert left",
        "columnMenuItemInsertRight": "Insert right",
        "columnMenuItemSortAsc": "Sort {{mode}}",
        "columnMenuItemSortDesc": "Sort {{mode}}",
        "columnMenuItemRemoveSort": "Remove Sort",
        "columnMenuItemFilter": "Filter",
        "columnMenuItemRemoveFilter": "Remove Filter",
        "columnMenuItemGroupBy": "Group by this column",
        "columnMenuItemRemoveGroupBy": "Remove Group",
        "columnMenuItemHide": "Hide",
        "columnMenuItemDelete": "Delete",
        "columnResizeTooltip": "width: {{value}}px",
        "rowResizeTooltip": "height: {{value}}px",
        "commandBarAddRow": "Add",
        "commandBarDeleteRow": "Delete",
        "commandBarBatchRevert": "Revert",
        "commandBarBatchSave": "Save",
        "commandBarFilter": "Filter",
        "commandBarSort": "Sort",
        "commandBarSearch": "Search",
        "commandBarCustomize": "Customize",
        "commandBarGroup": "Group",
        "commandColumnEdit": "Edit",
        "commandColumnDelete": "Delete",
        "commandColumnCancel": "Cancel",
        "commandColumnUpdate": "Update",
        "commandColumnMenu": "",
        "expandRow": "Expand row",
        "collapseRow": "Collapse row",
        "addNewRow": "Click here to add a new row",
        "addNewColumn": "Click here to add a new column",
        "dialogChartHeader": "{{value}} Chart",
        "dialogRowDetailHeader": "Row Id: {{value}}",
        "dialogDescriptionHeader": "Column: {{value}}",
        "dialogRowDetailButtonConfirm": "OK",
        "dialogRowDetailButtonCancel": "CANCEL",
        "dialogEditHeader": "Edit {{value}}",
        "dialogAddButtonConfirm": "ADD",
        "dialogAddButtonCancel": "CANCEL",
        "dialogEditButtonConfirm": "OK",
        "dialogEditButtonCancel": "CANCEL",
        "dialogFilterButtonConfirm": "FILTER",
        "dialogFilterButtonCancel": "CLEAR",
        "dialogDeleteButtonConfirm": "DELETE",
        "dialogDeleteButtonCancel": "CANCEL",
        "dialogEditColumn": "Column: {{value}}",
        "dialogAddColumn": "Add Column",
        "dialogAddHeader": "Add Row",
        "dialogDeleteHeader": "Delete Row",
        "dialogFilterHeader": "Filter by",
        "dialogFilterMinLabel": "Min",
        "dialogFilterMaxLabel": "Max",
        "conditionalFormatting": "Conditional Formatting",
        "groupBarLabel": "Drag a column header here to group by that column",
        "dialogDeleteContent": "Are you sure you want to delete this row?",
        "calendar": {
          "/": "/",
          ":": ":",
          "firstDay": 0,
          "days": {
            "names": [
              "Sunday",
              "Monday",
              "Tuesday",
              "Wednesday",
              "Thursday",
              "Friday",
              "Saturday"
            ],
            "namesAbbr": [
              "Sun",
              "Mon",
              "Tue",
              "Wed",
              "Thu",
              "Fri",
              "Sat"
            ],
            "namesShort": [
              "Su",
              "Mo",
              "Tu",
              "We",
              "Th",
              "Fr",
              "Sa"
            ]
          },
          "months": {
            "names": [
              "January",
              "February",
              "March",
              "April",
              "May",
              "June",
              "July",
              "August",
              "September",
              "October",
              "November",
              "December",
              ""
            ],
            "namesAbbr": [
              "Jan",
              "Feb",
              "Mar",
              "Apr",
              "May",
              "Jun",
              "Jul",
              "Aug",
              "Sep",
              "Oct",
              "Nov",
              "Dec",
              ""
            ]
          },
          "AM": [
            "AM",
            "am",
            "AM"
          ],
          "PM": [
            "PM",
            "pm",
            "PM"
          ],
          "eras": [
            {
              "name": "A.D.",
              "start": null,
              "offset": 0
            }
          ],
          "currencySymbol": "$",
          "currency": "USD",
          "currencySymbolPosition": "before",
          "decimalSeparator": ".",
          "thousandsSeparator": ","
        },
        "CONTAINS": "Contains",
        "DOES_NOT_CONTAIN": "Does not contain",
        "ENDS_WITH": "Ends with",
        "EQUAL": "Equal",
        "GREATER_THAN": "Greater than",
        "GREATER_THAN_OR_EQUAL": "Greater than or equal",
        "LESS_THAN": "Less than",
        "LESS_THAN_OR_EQUAL": "Less than or equal",
        "NOT_EQUAL": "Not equal",
        "RANGE": "Range",
        "CLEAR_FILTER": "Clear Filter",
        "STARTS_WITH": "Starts with",
        "addFilter": "+ Add filter",
        "and": "And",
        "apply": "Apply",
        "booleanFirst": "☐",
        "booleanLast": "☑",
        "cancel": "Cancel",
        "CONTAINS_CASE_SENSITIVE": "Contains (case sensitive)",
        "dateFirst": "1",
        "dateLast": "9",
        "DOES_NOT_CONTAIN_CASE_SENSITIVE": "does not contain (case sensitive)",
        "EMPTY": "empty",
        "ENDS_WITH_CASE_SENSITIVE": "ends with (case sensitive)",
        "EQUAL_CASE_SENSITIVE": "equal (case sensitive)",
        "filter": "Filter",
        "customize": "Customize Columns",
        "filteredByMultiple": "{{n}} filters",
        "filteredByOne": "1 filter",
        "filterValuePlaceholder": "Value",
        "find": "Find a field",
        "findInView": "Find in view",
        "firstBy": "Sort by",
        "found": "{{nth}} of {{n}}",
        "from": "from",
        "noFilters": "No filters applied",
        "noResults": "No results",
        "noSorting": "No sorting applied",
        "NOT_EMPTY": "not empty",
        "NOT_NULL": "not null",
        "NULL": "null",
        "numberFirst": "1",
        "numberLast": "9",
        "ok": "OK",
        "or": "Or",
        "pickAnother": "Pick another field to sort by",
        "sort": "Sort",
        "group": "Group",
        "sortedByMultiple": "Sorted by {{n}} fields",
        "sortedByOne": "Sorted by 1 field",
        "STARTS_WITH_CASE_SENSITIVE": "starts with (case sensitive)",
        "stringFirst": "A",
        "stringLast": "Z",
        "thenBy": "then by",
        "where": "Where",
        "collapseAll": "Collapse all",
        "expandAll": "Expand all",
        "noGrouping": "No grouping",
        "groupedByMultiple": "{{n}} groups",
        "groupedByOne": "1 group",
        "firstByGroup": "Group by",
        "pickAnotherGroupBy": "Pick another field to group by",
        "add": "Add condition",
        "all": "All columns",
        "between": "Between",
        "close": "Close",
        "column": "Column:",
        "condition": "Condition:",
        "equal": "Equal To",
        "fontFamily": "Font family:",
        "fontSize": "Font size:",
        "format": "Format:",
        "greaterThan": "Greater Than",
        "highlight": "Highlight",
        "lessThan": "Less Than",
        "notEqual": "Not Equal To",
        "remove": "Remove condition",
        "secondValue": "Second value:",
        "text": "Text",
        "value": "Value:",
        "addCondition": "Add Condition",
        "addGroup": "Add Group",
        "blanks": "(Blanks)",
        "clear": "Clear",
        "contains": "contains",
        "containsCaseSensitive": "contains (case sensitive)",
        "dateTabLabel": "DATE",
        "doesNotContain": "does not contain",
        "doesNotContainCaseSensitive": "does not contain (case sensitive)",
        "empty": "empty",
        "endsWith": "ends with",
        "endsWithCaseSensitive": "ends with (case sensitive)",
        "equalCaseSensitive": "equal (case sensitive)",
        "greaterThanOrEqual": "greater than or equal",
        "lessThanOrEqual": "less than or equal",
        "mismatchedProperties": "smartFilterPanel: The 'filterType' and the data type of the selected 'dataField' are mismatched.",
        "missingProperty": "smartFilterPanel: When mode is \"excel\", either \"data\" and \"dataField\" or \"dataSource\" of type Array have to be set.",
        "notEmpty": "not empty",
        "notNull": "not null",
        "null": "null ",
        "placeholderBoolean": "Select value",
        "placeholderDate": "Enter date",
        "placeholderNumber": "Enter number",
        "placeholderTime": "Enter time",
        "placeholderValue": "Enter value",
        "selectAll": "(Select All)",
        "showRows": "Show rows where:",
        "startsWith": "starts with",
        "startsWithCaseSensitive": "starts with (case sensitive)",
        "matchCase": "Match Case",
        "timeTabLabel": "TIME",
        "today": "Today",
        "formatColumn": "Format Column",
        "formating": "Conditional Formatting",
        "reset": "Reset",
        "filteredRecords": "All rows are filtered",
        "duplicateCells": "Clone column cells and settings",
        "duplicateSettings": "Clone column settings",
        "views": "Views",
        "noView": "No view",
        "myView": "My view",
        "saveView": "New view"
      },
      "de": {
        "invalidColumnProperty": "{{elementType}}: Ungültiger Eigenschaftsname \"{{propertyName}}\" für Spalte: \"{{type}}\"",
        "invalidRowProperty": "{{elementType}}: Ungültiger Eigenschaftsname \"{{propertyName}}\" für Zeile\"",
        "invalidCellValue": "Ungültiger Zellenwert \"{{value}}\", Validierungsregel: \"{{validationRule}}\"",
        "frozenColumns": "{{elementType}}: Um eine Spaltengruppe zu fixieren, müssen alle Spalten darin fixiert sein.",
        "frozenRows": "{{elementType}}: Um eine spezielle Zelle zu fixieren, müssen alle Zeilen darin fixiert sein.",
        "columnGroups": "{{elementType}}: Bitte überprüfen Sie die Initialisierung des Spaltengruppen-Arrays des smartGrids. Die Spalten in einer Spaltengruppe sollten Geschwister im Spalten-Array sein.",
        "min": "Min: {{value}}",
        "max": "Max: {{value}}",
        "sum": "Summe: {{value}}",
        "avg": "Durchschnitt: {{value}}",
        "count": "Anzahl: {{value}}",
        "pagerFirstButton": "Erste",
        "pagerLastButton": "Letzte",
        "pagerPreviousButton": "Vorherige",
        "pagerNextButton": "Nächste",
        "pagerNavigateToLabel": "Gehe zu:",
        "pagerPageSizeLabel": "Anzeigen:",
        "pagerNavigateToInputPlaceholder": "",
        "pagerEllipsis": "...",
        "pagerSummaryString": "von",
        "pagerSummaryPrefix": "von",
        "pagerSummarySuffix": "",
        "columnMenuCustomizeType": "Typ anpassen",
        "columnMenuItemRename": "Umbenennen",
        "columnMenuItemEditDescription": "Beschreibung bearbeiten",
        "columnMenuItemDuplicate": "Duplizieren",
        "columnMenuItemInsertLeft": "Links einfügen",
        "columnMenuItemInsertRight": "Rechts einfügen",
        "columnMenuItemSortAsc": "{{mode}} sortieren",
        "columnMenuItemSortDesc": "{{mode}} sortieren",
        "columnMenuItemRemoveSort": "Sortierung entfernen",
        "columnMenuItemFilter": "Filtern",
        "columnMenuItemRemoveFilter": "Filter entfernen",
        "columnMenuItemGroupBy": "Nach dieser Spalte gruppieren",
        "columnMenuItemRemoveGroupBy": "Gruppierung entfernen",
        "columnMenuItemHide": "Ausblenden",
        "columnMenuItemDelete": "Löschen",
        "columnResizeTooltip": "Breite: {{value}}px",
        "rowResizeTooltip": "Höhe: {{value}}px",
        "commandBarAddRow": "Hinzufügen",
        "commandBarDeleteRow": "Löschen",
        "commandBarBatchRevert": "Zurücksetzen",
        "commandBarBatchSave": "Speichern",
        "commandBarFilter": "Filtern",
        "commandBarSort": "Sortieren",
        "commandBarSearch": "Suchen",
        "commandBarCustomize": "Anpassen",
        "commandBarGroup": "Gruppieren",
        "commandColumnEdit": "Bearbeiten",
        "commandColumnDelete": "Löschen",
        "commandColumnCancel": "Abbrechen",
        "commandColumnUpdate": "Aktualisieren",
        "commandColumnMenu": "",
        "expandRow": "Zeile erweitern",
        "collapseRow": "Zeile ausblenden",
        "addNewRow": "Hier klicken, um eine neue Zeile hinzuzufügen",
        "addNewColumn": "Hier klicken, um eine neue Spalte hinzuzufügen",
        "dialogChartHeader": "{{value}} Diagramm",
        "dialogRowDetailHeader": "Zeilen-ID: {{value}}",
        "dialogDescriptionHeader": "Spalte: {{value}}",
        "dialogRowDetailButtonConfirm": "OK",
        "dialogRowDetailButtonCancel": "ABBRECHEN",
        "dialogEditHeader": "{{value}} bearbeiten",
        "dialogAddButtonConfirm": "HINZUFÜGEN",
        "dialogAddButtonCancel": "ABBRECHEN",
        "dialogEditButtonConfirm": "OK",
        "dialogEditButtonCancel": "ABBRECHEN",
        "dialogFilterButtonConfirm": "FILTERN",
        "dialogFilterButtonCancel": "LEEREN",
        "dialogDeleteButtonConfirm": "LÖSCHEN",
        "dialogDeleteButtonCancel": "ABBRECHEN",
        "dialogEditColumn": "Spalte: {{value}}",
        "dialogAddColumn": "Spalte hinzufügen",
        "dialogAddHeader": "Zeile hinzufügen",
        "dialogDeleteHeader": "Zeile löschen",
        "dialogFilterHeader": "Filtern nach",
        "dialogFilterMinLabel": "Min",
        "dialogFilterMaxLabel": "Max",
        "conditionalFormatting": "Bedingte Formatierung",
        "groupBarLabel": "Ziehen Sie eine Spaltenüberschrift hierher, um nach dieser Spalte zu gruppieren",
        "dialogDeleteContent": "Möchten Sie diese Zeile wirklich löschen?",
        "calendar": {
          "/": "/",
          ":": ":",
          "firstDay": 0,
          "days": {
            "names": [
              "Sonntag",
              "Montag",
              "Dienstag",
              "Mittwoch",
              "Donnerstag",
              "Freitag",
              "Samstag"
            ],
            "namesAbbr": [
              "So",
              "Mo",
              "Di",
              "Mi",
              "Do",
              "Fr",
              "Sa"
            ],
            "namesShort": [
              "So",
              "Mo",
              "Di",
              "Mi",
              "Do",
              "Fr",
              "Sa"
            ]
          },
          "months": {
            "names": [
              "Januar",
              "Februar",
              "März",
              "April",
              "Mai",
              "Juni",
              "Juli",
              "August",
              "September",
              "Oktober",
              "November",
              "Dezember",
              ""
            ],
            "namesAbbr": [
              "Jan",
              "Feb",
              "Mär",
              "Apr",
              "Mai",
              "Jun",
              "Jul",
              "Aug",
              "Sep",
              "Okt",
              "Nov",
              "Dez",
              ""
            ]
          },
          "AM": [
            "AM",
            "am",
            "AM"
          ],
          "PM": [
            "PM",
            "pm",
            "PM"
          ],
          "eras": [
            {
              "name": "A.D.",
              "start": null,
              "offset": 0
            }
          ],
          "currencySymbol": "€",
          "currency": "EUR",
          "currencySymbolPosition": "before",
          "decimalSeparator": ",",
          "thousandsSeparator": "."
        },
        "CONTAINS": "Enthält",
        "DOES_NOT_CONTAIN": "Enthält nicht",
        "ENDS_WITH": "Endet mit",
        "EQUAL": "Gleich",
        "GREATER_THAN": "Größer als",
        "GREATER_THAN_OR_EQUAL": "Größer als oder gleich",
        "LESS_THAN": "Kleiner als",
        "LESS_THAN_OR_EQUAL": "Kleiner als oder gleich",
        "NOT_EQUAL": "Ungleich",
        "RANGE": "Bereich",
        "CLEAR_FILTER": "Filter löschen",
        "STARTS_WITH": "Beginnt mit",
        "addFilter": "+ Filter hinzufügen",
        "and": "Und",
        "apply": "Anwenden",
        "booleanFirst": "☐",
        "booleanLast": "☑",
        "cancel": "Abbrechen",
        "CONTAINS_CASE_SENSITIVE": "Enthält (Groß-/Kleinschreibung beachten)",
        "dateFirst": "1",
        "dateLast": "9",
        "DOES_NOT_CONTAIN_CASE_SENSITIVE": "Enthält nicht (Groß-/Kleinschreibung beachten)",
        "EMPTY": "Leer",
        "ENDS_WITH_CASE_SENSITIVE": "Endet mit (Groß-/Kleinschreibung beachten)",
        "EQUAL_CASE_SENSITIVE": "Gleich (Groß-/Kleinschreibung beachten)",
        "filter": "Filtern",
        "customize": "Spalten anpassen",
        "filteredByMultiple": "{{n}} Filter",
        "filteredByOne": "1 Filter",
        "filterValuePlaceholder": "Wert",
        "find": "Feld suchen",
        "findInView": "Im Ansichtsfenster suchen",
        "firstBy": "Sortieren nach",
        "found": "{{nth}} von {{n}}",
        "from": "von",
        "noFilters": "Keine Filter angewendet",
        "noResults": "Keine Ergebnisse",
        "noSorting": "Keine Sortierung angewendet",
        "NOT_EMPTY": "Nicht leer",
        "NOT_NULL": "Nicht null",
        "NULL": "Null",
        "numberFirst": "1",
        "numberLast": "9",
        "ok": "OK",
        "or": "Oder",
        "pickAnother": "Wählen Sie ein anderes Feld zum Sortieren aus",
        "sort": "Sortieren",
        "group": "Gruppieren",
        "sortedByMultiple": "Sortiert nach {{n}} Feldern",
        "sortedByOne": "Sortiert nach 1 Feld",
        "STARTS_WITH_CASE_SENSITIVE": "Beginnt mit (Groß-/Kleinschreibung beachten)",
        "stringFirst": "A",
        "stringLast": "Z",
        "thenBy": "dann nach",
        "where": "Wo",
        "collapseAll": "Alle ausblenden",
        "expandAll": "Alle erweitern",
        "noGrouping": "Keine Gruppierung",
        "groupedByMultiple": "{{n}} Gruppen",
        "groupedByOne": "1 Gruppe",
        "firstByGroup": "Nach",
        "pickAnotherGroupBy": "Wählen Sie ein anderes Feld zum Gruppieren aus",
        "add": "Bedingung hinzufügen",
        "addGroup": "Gruppe hinzufügen",
        "blanks": "(Leer)",
        "clear": "Leeren",
        "contains": "enthält",
        "containsCaseSensitive": "enthält (Groß-/Kleinschreibung beachten)",
        "dateTabLabel": "DATUM",
        "doesNotContain": "enthält nicht",
        "doesNotContainCaseSensitive": "enthält nicht (Groß-/Kleinschreibung beachten)",
        "empty": "leer",
        "endsWith": "endet mit",
        "endsWithCaseSensitive": "endet mit (Groß-/Kleinschreibung beachten)",
        "equalCaseSensitive": "gleich (Groß-/Kleinschreibung beachten)",
        "greaterThanOrEqual": "größer als oder gleich",
        "lessThanOrEqual": "kleiner als oder gleich",
        "mismatchedProperties": "smartFilterPanel: Der 'filterType' und der Datentyp des ausgewählten 'dataField' passen nicht zusammen.",
        "missingProperty": "smartFilterPanel: Wenn der Modus \"Excel\" ist, müssen entweder \"data\" und \"dataField\" oder \"dataSource\" vom Typ Array festgelegt werden.",
        "notEmpty": "nicht leer",
        "notNull": "nicht null",
        "null": "null",
        "placeholderBoolean": "Wert auswählen",
        "placeholderDate": "Datum eingeben",
        "placeholderNumber": "Nummer eingeben",
        "placeholderTime": "Uhrzeit eingeben",
        "placeholderValue": "Wert eingeben",
        "selectAll": "(Alle auswählen)",
        "showRows": "Zeige Zeilen, in denen:",
        "startsWith": "beginnt mit",
        "startsWithCaseSensitive": "beginnt mit (Groß-/Kleinschreibung beachten)",
        "matchCase": "Groß-/Kleinschreibung beachten",
        "timeTabLabel": "UHRZEIT",
        "today": "Heute",
        "formatColumn": "Spalte formatieren",
        "formating": "Bedingte Formatierung",
        "reset": "Zurücksetzen",
        "filteredRecords": "Alle Zeilen sind gefiltert",
        "duplicateCells": "Spaltenzellen und Einstellungen duplizieren",
        "duplicateSettings": "Spalteneinstellungen duplizieren",
        "views": "Ansichten",
        "noView": "Keine Ansicht",
        "myView": "Meine Ansicht",
        "saveView": "Neue Ansicht speichern"
      },
      "fr": {
        "invalidColumnProperty": "{{elementType}}: Nom de propriété invalide \"{{propertyName}}\" défini pour la colonne : \"{{type}}\"",
        "invalidRowProperty": "{{elementType}}: Nom de propriété invalide \"{{propertyName}}\" défini pour la ligne\"",
        "invalidCellValue": "Valeur de cellule invalide \"{{value}}\", Règle de validation : \"{{validationRule}}\"",
        "frozenColumns": "{{elementType}}: Pour épingler une groupe de colonnes, toutes les colonnes à l'intérieur doivent être figées.",
        "frozenRows": "{{elementType}}: Pour épingler une cellule spéciale, toutes les lignes à l'intérieur doivent être figées.",
        "columnGroups": "{{elementType}}: Veuillez vérifier l'initialisation du tableau de colonnes du smartGrid. Les colonnes d'un groupe de colonnes doivent être des frères dans le tableau de colonnes.",
        "min": "Min : {{value}}",
        "max": "Max : {{value}}",
        "sum": "Somme : {{value}}",
        "avg": "Moyenne : {{value}}",
        "count": "Nombre : {{value}}",
        "pagerFirstButton": "Première",
        "pagerLastButton": "Dernière",
        "pagerPreviousButton": "Précédente",
        "pagerNextButton": "Suivante",
        "pagerNavigateToLabel": "Aller à :",
        "pagerPageSizeLabel": "Afficher :",
        "pagerNavigateToInputPlaceholder": "",
        "pagerEllipsis": "...",
        "pagerSummaryString": "de",
        "pagerSummaryPrefix": "de",
        "pagerSummarySuffix": "",
        "columnMenuCustomizeType": "Personnaliser le type",
        "columnMenuItemRename": "Renommer",
        "columnMenuItemEditDescription": "Modifier la description",
        "columnMenuItemDuplicate": "Dupliquer",
        "columnMenuItemInsertLeft": "Insérer à gauche",
        "columnMenuItemInsertRight": "Insérer à droite",
        "columnMenuItemSortAsc": "Trier {{mode}}",
        "columnMenuItemSortDesc": "Trier {{mode}}",
        "columnMenuItemRemoveSort": "Supprimer le tri",
        "columnMenuItemFilter": "Filtrer",
        "columnMenuItemRemoveFilter": "Supprimer le filtre",
        "columnMenuItemGroupBy": "Grouper par cette colonne",
        "columnMenuItemRemoveGroupBy": "Supprimer le regroupement",
        "columnMenuItemHide": "Masquer",
        "columnMenuItemDelete": "Supprimer",
        "columnResizeTooltip": "Largeur : {{value}}px",
        "rowResizeTooltip": "Hauteur : {{value}}px",
        "commandBarAddRow": "Ajouter",
        "commandBarDeleteRow": "Supprimer",
        "commandBarBatchRevert": "Annuler",
        "commandBarBatchSave": "Enregistrer",
        "commandBarFilter": "Filtrer",
        "commandBarSort": "Trier",
        "commandBarSearch": "Rechercher",
        "commandBarCustomize": "Personnaliser",
        "commandBarGroup": "Regrouper",
        "commandColumnEdit": "Modifier",
        "commandColumnDelete": "Supprimer",
        "commandColumnCancel": "Annuler",
        "commandColumnUpdate": "Mettre à jour",
        "commandColumnMenu": "",
        "expandRow": "Développer la ligne",
        "collapseRow": "Réduire la ligne",
        "addNewRow": "Cliquez ici pour ajouter une nouvelle ligne",
        "addNewColumn": "Cliquez ici pour ajouter une nouvelle colonne",
        "dialogChartHeader": "Diagramme {{value}}",
        "dialogRowDetailHeader": "ID de ligne : {{value}}",
        "dialogDescriptionHeader": "Colonne : {{value}}",
        "dialogRowDetailButtonConfirm": "OK",
        "dialogRowDetailButtonCancel": "ANNULER",
        "dialogEditHeader": "Modifier {{value}}",
        "dialogAddButtonConfirm": "AJOUTER",
        "dialogAddButtonCancel": "ANNULER",
        "dialogEditButtonConfirm": "OK",
        "dialogEditButtonCancel": "ANNULER",
        "dialogFilterButtonConfirm": "FILTRER",
        "dialogFilterButtonCancel": "EFFACER",
        "dialogDeleteButtonConfirm": "SUPPRIMER",
        "dialogDeleteButtonCancel": "ANNULER",
        "dialogEditColumn": "Colonne : {{value}}",
        "dialogAddColumn": "Ajouter une colonne",
        "dialogAddHeader": "Ajouter une ligne",
        "dialogDeleteHeader": "Supprimer une ligne",
        "dialogFilterHeader": "Filtrer par",
        "dialogFilterMinLabel": "Min",
        "dialogFilterMaxLabel": "Max",
        "conditionalFormatting": "Mise en forme conditionnelle",
        "groupBarLabel": "Faites glisser un en-tête de colonne ici pour grouper par cette colonne",
        "dialogDeleteContent": "Voulez-vous vraiment supprimer cette ligne ?",
        "calendar": {
          "/": "/",
          ":": ":",
          "firstDay": 0,
          "days": {
            "names": [
              "Dimanche",
              "Lundi",
              "Mardi",
              "Mercredi",
              "Jeudi",
              "Vendredi",
              "Samedi"
            ],
            "namesAbbr": [
              "Dim",
              "Lun",
              "Mar",
              "Mer",
              "Jeu",
              "Ven",
              "Sam"
            ],
            "namesShort": [
              "Di",
              "Lu",
              "Ma",
              "Me",
              "Je",
              "Ve",
              "Sa"
            ]
          },
          "months": {
            "names": [
              "Janvier",
              "Février",
              "Mars",
              "Avril",
              "Mai",
              "Juin",
              "Juillet",
              "Août",
              "Septembre",
              "Octobre",
              "Novembre",
              "Décembre",
              ""
            ],
            "namesAbbr": [
              "Jan",
              "Fév",
              "Mar",
              "Avr",
              "Mai",
              "Juin",
              "Juil",
              "Août",
              "Sept",
              "Oct",
              "Nov",
              "Déc",
              ""
            ]
          },
          "AM": [
            "AM",
            "am",
            "AM"
          ],
          "PM": [
            "PM",
            "pm",
            "PM"
          ],
          "eras": [
            {
              "name": "après J.-C.",
              "start": null,
              "offset": 0
            }
          ],
          "currencySymbol": "€",
          "currency": "EUR",
          "currencySymbolPosition": "before",
          "decimalSeparator": ",",
          "thousandsSeparator": " "
        },
        "CONTAINS": "Contient",
        "DOES_NOT_CONTAIN": "Ne contient pas",
        "ENDS_WITH": "Se termine par",
        "EQUAL": "Égal",
        "GREATER_THAN": "Supérieur à",
        "GREATER_THAN_OR_EQUAL": "Supérieur ou égal à",
        "LESS_THAN": "Inférieur à",
        "LESS_THAN_OR_EQUAL": "Inférieur ou égal à",
        "NOT_EQUAL": "Différent",
        "RANGE": "Plage",
        "CLEAR_FILTER": "Effacer le filtre",
        "STARTS_WITH": "Commence par",
        "addFilter": "+ Ajouter un filtre",
        "and": "Et",
        "apply": "Appliquer",
        "booleanFirst": "☐",
        "booleanLast": "☑",
        "cancel": "Annuler",
        "CONTAINS_CASE_SENSITIVE": "Contient (sensible à la casse)",
        "dateFirst": "1",
        "dateLast": "9",
        "DOES_NOT_CONTAIN_CASE_SENSITIVE": "Ne contient pas (sensible à la casse)",
        "EMPTY": "Vide",
        "ENDS_WITH_CASE_SENSITIVE": "Se termine par (sensible à la casse)",
        "EQUAL_CASE_SENSITIVE": "Égal (sensible à la casse)",
        "filter": "Filtrer",
        "customize": "Personnaliser les colonnes",
        "filteredByMultiple": "{{n}} filtres",
        "filteredByOne": "1 filtre",
        "filterValuePlaceholder": "Valeur",
        "find": "Rechercher un champ",
        "findInView": "Rechercher dans la vue",
        "firstBy": "Trier par",
        "found": "{{nth}} sur {{n}}",
        "from": "de",
        "noFilters": "Aucun filtre appliqué",
        "noResults": "Aucun résultat",
        "noSorting": "Aucun tri appliqué",
        "NOT_EMPTY": "Non vide",
        "NOT_NULL": "Non nul",
        "NULL": "Nul",
        "numberFirst": "1",
        "numberLast": "9",
        "ok": "OK",
        "or": "Ou",
        "pickAnother": "Choisir un autre champ pour trier par",
        "sort": "Trier",
        "group": "Regrouper",
        "sortedByMultiple": "Trié par {{n}} champs",
        "sortedByOne": "Trié par 1 champ",
        "STARTS_WITH_CASE_SENSITIVE": "Commence par (sensible à la casse)",
        "stringFirst": "A",
        "stringLast": "Z",
        "thenBy": "puis par",
        "where": "Où",
        "collapseAll": "Tout réduire",
        "expandAll": "Tout développer",
        "noGrouping": "Aucun regroupement",
        "groupedByMultiple": "{{n}} groupes",
        "groupedByOne": "1 groupe",
        "firstByGroup": "Regrouper par",
        "pickAnotherGroupBy": "Choisir un autre champ pour regrouper par",
        "add": "Ajouter une condition",
        "addGroup": "Ajouter un groupe",
        "blanks": "(Vides)",
        "clear": "Effacer",
        "contains": "contient",
        "containsCaseSensitive": "contient (sensible à la casse)",
        "dateTabLabel": "DATE",
        "doesNotContain": "ne contient pas",
        "doesNotContainCaseSensitive": "ne contient pas (sensible à la casse)",
        "empty": "vide",
        "endsWith": "se termine par",
        "endsWithCaseSensitive": "se termine par (sensible à la casse)",
        "equalCaseSensitive": "égal (sensible à la casse)",
        "greaterThanOrEqual": "supérieur ou égal à",
        "lessThanOrEqual": "inférieur ou égal à",
        "mismatchedProperties": "smartFilterPanel : Le 'filterType' et le type de données du 'dataField' sélectionné ne correspondent pas.",
        "missingProperty": "smartFilterPanel : Lorsque le mode est \"excel\", soit \"data\" et \"dataField\", soit \"dataSource\" de type Array doivent être définis.",
        "notEmpty": "non vide",
        "notNull": "non nul",
        "null": "nul",
        "placeholderBoolean": "Sélectionner une valeur",
        "placeholderDate": "Entrer une date",
        "placeholderNumber": "Entrer un nombre",
        "placeholderTime": "Entrer une heure",
        "placeholderValue": "Entrer une valeur",
        "selectAll": "(Tout sélectionner)",
        "showRows": "Afficher les lignes où :",
        "startsWith": "commence par",
        "startsWithCaseSensitive": "commence par (sensible à la casse)",
        "matchCase": "Respecter la casse",
        "timeTabLabel": "HEURE",
        "today": "Aujourd'hui",
        "formatColumn": "Formatter la colonne",
        "formating": "Mise en forme conditionnelle",
        "reset": "Réinitialiser",
        "filteredRecords": "Toutes les lignes sont filtrées",
        "duplicateCells": "Dupliquer les cellules de la colonne et les paramètres",
        "duplicateSettings": "Dupliquer les paramètres de la colonne",
        "views": "Vues",
        "noView": "Aucune vue",
        "myView": "Ma vue",
        "saveView": "Nouvelle vue enregistrer"
      },
      "es": {
        "invalidColumnProperty": "{{elementType}}: Nombre de propiedad no válido \"{{propertyName}}\" establecido para la columna: \"{{type}}\"",
        "invalidRowProperty": "{{elementType}}: Nombre de propiedad no válido \"{{propertyName}}\" establecido para la fila\"",
        "invalidCellValue": "Valor de celda no válido \"{{value}}\", Regla de validación: \"{{validationRule}}\"",
        "frozenColumns": "{{elementType}}: Para anclar un grupo de columnas, todas las columnas dentro de él deben estar congeladas.",
        "frozenRows": "{{elementType}}: Para anclar una celda especial, todas las filas dentro de ella deben estar congeladas.",
        "columnGroups": "{{elementType}}: Por favor, revisa la inicialización del array de columnas de smartGrid. Se espera que las columnas en un grupo de columnas sean hermanas en el array de columnas.",
        "min": "Mín: {{value}}",
        "max": "Máx: {{value}}",
        "sum": "Suma: {{value}}",
        "avg": "Promedio: {{value}}",
        "count": "Conteo: {{value}}",
        "pagerFirstButton": "Primero",
        "pagerLastButton": "Último",
        "pagerPreviousButton": "Anterior",
        "pagerNextButton": "Siguiente",
        "pagerNavigateToLabel": "Ir a:",
        "pagerPageSizeLabel": "Mostrar:",
        "pagerNavigateToInputPlaceholder": "",
        "pagerEllipsis": "...",
        "pagerSummaryString": "de",
        "pagerSummaryPrefix": "de",
        "pagerSummarySuffix": "",
        "columnMenuCustomizeType": "Personalizar tipo",
        "columnMenuItemRename": "Cambiar nombre",
        "columnMenuItemEditDescription": "Editar descripción",
        "columnMenuItemDuplicate": "Duplicar",
        "columnMenuItemInsertLeft": "Insertar a la izquierda",
        "columnMenuItemInsertRight": "Insertar a la derecha",
        "columnMenuItemSortAsc": "Ordenar {{mode}}",
        "columnMenuItemSortDesc": "Ordenar {{mode}}",
        "columnMenuItemRemoveSort": "Eliminar ordenamiento",
        "columnMenuItemFilter": "Filtrar",
        "columnMenuItemRemoveFilter": "Eliminar filtro",
        "columnMenuItemGroupBy": "Agrupar por esta columna",
        "columnMenuItemRemoveGroupBy": "Eliminar agrupamiento",
        "columnMenuItemHide": "Ocultar",
        "columnMenuItemDelete": "Eliminar",
        "columnResizeTooltip": "Ancho: {{value}}px",
        "rowResizeTooltip": "Altura: {{value}}px",
        "commandBarAddRow": "Agregar",
        "commandBarDeleteRow": "Eliminar",
        "commandBarBatchRevert": "Deshacer",
        "commandBarBatchSave": "Guardar",
        "commandBarFilter": "Filtrar",
        "commandBarSort": "Ordenar",
        "commandBarSearch": "Buscar",
        "commandBarCustomize": "Personalizar",
        "commandBarGroup": "Agrupar",
        "commandColumnEdit": "Editar",
        "commandColumnDelete": "Eliminar",
        "commandColumnCancel": "Cancelar",
        "commandColumnUpdate": "Actualizar",
        "commandColumnMenu": "",
        "expandRow": "Expandir fila",
        "collapseRow": "Colapsar fila",
        "addNewRow": "Haz clic aquí para agregar una nueva fila",
        "addNewColumn": "Haz clic aquí para agregar una nueva columna",
        "dialogChartHeader": "Gráfico de {{value}}",
        "dialogRowDetailHeader": "ID de fila: {{value}}",
        "dialogDescriptionHeader": "Columna: {{value}}",
        "dialogRowDetailButtonConfirm": "Aceptar",
        "dialogRowDetailButtonCancel": "CANCELAR",
        "dialogEditHeader": "Editar {{value}}",
        "dialogAddButtonConfirm": "AGREGAR",
        "dialogAddButtonCancel": "CANCELAR",
        "dialogEditButtonConfirm": "Aceptar",
        "dialogEditButtonCancel": "CANCELAR",
        "dialogFilterButtonConfirm": "FILTRAR",
        "dialogFilterButtonCancel": "LIMPIAR",
        "dialogDeleteButtonConfirm": "ELIMINAR",
        "dialogDeleteButtonCancel": "CANCELAR",
        "dialogEditColumn": "Columna: {{value}}",
        "dialogAddColumn": "Agregar columna",
        "dialogAddHeader": "Agregar fila",
        "dialogDeleteHeader": "Eliminar fila",
        "dialogFilterHeader": "Filtrar por",
        "dialogFilterMinLabel": "Mín",
        "dialogFilterMaxLabel": "Máx",
        "conditionalFormatting": "Formato condicional",
        "groupBarLabel": "Arrastra un encabezado de columna aquí para agrupar por esa columna",
        "dialogDeleteContent": "¿Estás seguro de que deseas eliminar esta fila?",
        "calendar": {
          "/": "/",
          ":": ":",
          "firstDay": 0,
          "days": {
            "names": [
              "Domingo",
              "Lunes",
              "Martes",
              "Miércoles",
              "Jueves",
              "Viernes",
              "Sábado"
            ],
            "namesAbbr": [
              "Dom",
              "Lun",
              "Mar",
              "Mié",
              "Jue",
              "Vie",
              "Sáb"
            ],
            "namesShort": [
              "Do",
              "Lu",
              "Ma",
              "Mi",
              "Ju",
              "Vi",
              "Sá"
            ]
          },
          "months": {
            "names": [
              "Enero",
              "Febrero",
              "Marzo",
              "Abril",
              "Mayo",
              "Junio",
              "Julio",
              "Agosto",
              "Septiembre",
              "Octubre",
              "Noviembre",
              "Diciembre",
              ""
            ],
            "namesAbbr": [
              "Ene",
              "Feb",
              "Mar",
              "Abr",
              "May",
              "Jun",
              "Jul",
              "Ago",
              "Sep",
              "Oct",
              "Nov",
              "Dic",
              ""
            ]
          },
          "AM": [
            "AM",
            "am",
            "AM"
          ],
          "PM": [
            "PM",
            "pm",
            "PM"
          ],
          "eras": [
            {
              "name": "d.C.",
              "start": null,
              "offset": 0
            }
          ],
          "currencySymbol": "$",
          "currency": "USD",
          "currencySymbolPosition": "before",
          "decimalSeparator": ",",
          "thousandsSeparator": "."
        },
        "CONTAINS": "Contiene",
        "DOES_NOT_CONTAIN": "No contiene",
        "ENDS_WITH": "Termina con",
        "EQUAL": "Igual",
        "GREATER_THAN": "Mayor que",
        "GREATER_THAN_OR_EQUAL": "Mayor o igual que",
        "LESS_THAN": "Menor que",
        "LESS_THAN_OR_EQUAL": "Menor o igual que",
        "NOT_EQUAL": "No igual",
        "RANGE": "Rango",
        "CLEAR_FILTER": "Limpiar filtro",
        "STARTS_WITH": "Empieza con",
        "addFilter": "+ Agregar filtro",
        "and": "Y",
        "apply": "Aplicar",
        "booleanFirst": "☐",
        "booleanLast": "☑",
        "cancel": "Cancelar",
        "CONTAINS_CASE_SENSITIVE": "Contiene (distingue mayúsculas y minúsculas)",
        "dateFirst": "1",
        "dateLast": "9",
        "DOES_NOT_CONTAIN_CASE_SENSITIVE": "No contiene (distingue mayúsculas y minúsculas)",
        "EMPTY": "Vacío",
        "ENDS_WITH_CASE_SENSITIVE": "Termina con (distingue mayúsculas y minúsculas)",
        "EQUAL_CASE_SENSITIVE": "Igual (distingue mayúsculas y minúsculas)",
        "filter": "Filtrar",
        "customize": "Personalizar columnas",
        "filteredByMultiple": "{{n}} filtros",
        "filteredByOne": "1 filtro",
        "filterValuePlaceholder": "Valor",
        "find": "Buscar campo",
        "findInView": "Buscar en vista",
        "firstBy": "Ordenar por",
        "found": "{{nth}} de {{n}}",
        "from": "de",
        "noFilters": "No se aplican filtros",
        "noResults": "No hay resultados",
        "noSorting": "No se aplica ordenamiento",
        "NOT_EMPTY": "No vacío",
        "NOT_NULL": "No nulo",
        "NULL": "Nulo",
        "numberFirst": "1",
        "numberLast": "9",
        "ok": "Aceptar",
        "or": "O",
        "pickAnother": "Selecciona otro campo para ordenar por",
        "sort": "Ordenar",
        "group": "Agrupar",
        "sortedByMultiple": "Ordenado por {{n}} campos",
        "sortedByOne": "Ordenado por 1 campo",
        "STARTS_WITH_CASE_SENSITIVE": "Empieza con (distingue mayúsculas y minúsculas)",
        "stringFirst": "A",
        "stringLast": "Z",
        "thenBy": "luego por",
        "where": "Donde",
        "collapseAll": "Colapsar todo",
        "expandAll": "Expandir todo",
        "noGrouping": "Sin agrupamiento",
        "groupedByMultiple": "{{n}} grupos",
        "groupedByOne": "1 grupo",
        "firstByGroup": "Agrupar por",
        "pickAnotherGroupBy": "Selecciona otro campo para agrupar por",
        "add": "Agregar condición",
        "all": "Todas las columnas",
        "between": "Entre",
        "close": "Cerrar",
        "column": "Columna:",
        "condition": "Condición:",
        "equal": "Igual a",
        "fontFamily": "Fuente:",
        "fontSize": "Tamaño de fuente:",
        "format": "Formato:",
        "greaterThan": "Mayor que",
        "highlight": "Resaltar",
        "lessThan": "Menor que",
        "notEqual": "No igual a",
        "remove": "Eliminar condición",
        "secondValue": "Segundo valor:",
        "text": "Texto",
        "value": "Valor:",
        "addCondition": "Agregar condición",
        "addGroup": "Agregar grupo",
        "blanks": "(Vacíos)",
        "clear": "Limpiar",
        "contains": "contiene",
        "containsCaseSensitive": "contiene (distingue mayúsculas y minúsculas)",
        "dateTabLabel": "FECHA",
        "doesNotContain": "no contiene",
        "doesNotContainCaseSensitive": "no contiene (distingue mayúsculas y minúsculas)",
        "empty": "vacío",
        "endsWith": "termina con",
        "endsWithCaseSensitive": "termina con (distingue mayúsculas y minúsculas)",
        "equalCaseSensitive": "igual (distingue mayúsculas y minúsculas)",
        "greaterThanOrEqual": "mayor o igual que",
        "lessThanOrEqual": "menor o igual que",
        "mismatchedProperties": "smartFilterPanel: El 'filterType' y el tipo de datos del 'dataField' seleccionado no coinciden.",
        "missingProperty": "smartFilterPanel: Cuando el modo es \"excel\", debe establecerse \"data\" y \"dataField\", o \"dataSource\" de tipo Array.",
        "notEmpty": "no vacío",
        "notNull": "no nulo",
        "null": "nulo",
        "placeholderBoolean": "Seleccionar valor",
        "placeholderDate": "Introducir fecha",
        "placeholderNumber": "Introducir número",
        "placeholderTime": "Introducir hora",
        "placeholderValue": "Introducir valor",
        "selectAll": "(Seleccionar todo)",
        "showRows": "Mostrar filas donde:",
        "startsWith": "empieza con",
        "startsWithCaseSensitive": "empieza con (distingue mayúsculas y minúsculas)",
        "matchCase": "Coincidir mayúsculas y minúsculas",
        "timeTabLabel": "HORA",
        "today": "Hoy",
        "formatColumn": "Formato de columna",
        "formating": "Formato condicional",
        "reset": "Restablecer",
        "filteredRecords": "Todas las filas están filtradas",
        "duplicateCells": "Clonar celdas y configuración de columna",
        "duplicateSettings": "Clonar configuración de columna",
        "views": "Vistas",
        "noView": "Sin vista",
        "myView": "Mi vista",
        "saveView": "Nueva vista"
      },
    }

    return gridMessages
  }

  getGridColumnLabels(locale?: Locale) { return this.gridColumnLabels[locale || this.locale] }

  getGridColumnGroupLabels(locale?: Locale) { return this.gridColumnGroupLabels[locale || this.locale] }

  getLocale() { return this.locale }

  getTrendString(locale?: Locale) {
    const trendTranslations = {
      en: 'Trend',
      de: 'Trend',
      fr: 'Tendance',
      es: 'Tendencia'
    }

    return trendTranslations[locale || this.locale]
  }

  getVolumeString(locale?: Locale) {
    const volumeTranslations = {
      en: 'Volume',
      de: 'Volumen',
      fr: 'Volume',
      es: 'Volumen'
    }

    return volumeTranslations[locale || this.locale]
  }

  getTeamEfficiencyString(locale?: Locale) {
    const teamEfficiencyTranslations = {
      en: 'Team Efficiency',
      de: 'Team-Effizienz',
      fr: "Efficacité de l'équipe",
      es: 'Eficiencia del equipo'
    }

    return teamEfficiencyTranslations[locale || this.locale]
  }

  getTeamCalendarString(locale?: Locale) {

    const teamCalendarTranslations = {
      en: 'Team calendar',
      de: 'Teamkalender',
      fr: "Calendrier d'équipe",
      es: 'Calendario del equipo'
    }

    return teamCalendarTranslations[locale || this.locale]
  }

  getShowWorkingHoursString(locale?: Locale) {

    const showWorkingHourTranslations = {
      en: 'Show working hours',
      de: 'Arbeitszeiten anzeigen',
      fr: 'Afficher les heures de travail',
      es: 'Mostrar horas de trabajo'
    }

    return showWorkingHourTranslations[locale || this.locale]
  }

  getShowFullDayString(locale?: Locale) {

    const showFullDayTranslations = {
      en: 'Show full day',
      de: 'Ganzen Tag anzeigen',
      fr: 'Afficher la journée complète',
      es: 'Mostrar día completo'
    }

    return showFullDayTranslations[locale || this.locale]
  }

  getSchedulerMessages(locale?: Locale) {
    const messages = {
      "en": {
        "propertyUnknownName": "Invalid property name: '{{name}}'!",
        "propertyUnknownType": "'{{name}}' property is with undefined 'type' member!",
        "propertyInvalidValue": "Invalid '{{name}}' property value! Actual value: '{{actualValue}}', Expected value: '{{value}}'!",
        "propertyInvalidValueType": "Invalid '{{name}}' property value type! Actual type: '{{actualType}}', Expected type: '{{type}}'!",
        "methodInvalidValueType": "Invalid '{{name}}' method argument value type! Actual type: '{{actualType}}', Expected type: '{{type}}' for argument with index: '{{argumentIndex}}'!",
        "methodInvalidArgumentsCount": "Invalid '{{name}}' method arguments count! Actual arguments count: '{{actualArgumentsCount}}', Expected at least: '{{argumentsCount}}' argument(s)!",
        "methodInvalidReturnType": "Invalid '{{name}}' method return type! Actual type: '{{actualType}}', Expected type: '{{type}}'!",
        "elementNotInDOM": "Element does not exist in DOM! Please, add the element to the DOM, before invoking a method.",
        "moduleUndefined": "Module is undefined.",
        "missingReference": "{{elementType}}: Missing reference to '{{files}}'.",
        "htmlTemplateNotSuported": "{{elementType}}: Web Browser doesn't support HTMLTemplate elements.",
        "invalidTemplate": "{{elementType}}: '{{property}}' property accepts a string that must match the id of an HTMLTemplate element from the DOM.",
        "invalidValue": "{{elementType}}: Invalid {{property}} value. {{property}} should be of type {{typeOne}} or {{typeTwo}}.",
        "invalidTimeZone": "{{elementType}}: Invalid timeZone value. TimeZone should be the id of an allowed timeZone value.",
        "incorrectArgument": "{{elementType}}: Incorrect argument {{argumentName}} in method {{methodName}}.",
        "noId": "smartScheduler requires an id in order to save/load/clear a state.",
        "agenda": "Agenda",
        "agendaPlaceholder": "No events to display",
        "day": "Day",
        "week": "Week",
        "workWeek": "Work Week",
        "month": "Month",
        "allDay": "All Day",
        "timelineDay": "Timeline Day",
        "timelineWeek": "Timeline Week",
        "timelineMonth": "Timeline Month",
        "newEvent": "New Event",
        "ok": "Ok",
        "cancel": "Cancel",
        "delete": "Delete",
        "label": "Label",
        "dateStart": "Start Date",
        "dateEnd": "End Date",
        "repeat": "Repeat",
        "description": "Description",
        "repeatFreq": "Repeat",
        "repeatInterval": "Repeat Every",
        "repeatOn": "Repeat On",
        "repeatEnd": "End Repeat",
        "repeatEndOption": "Never",
        "repeatEndOnOption": "On",
        "repeatEndAfterOption": "After",
        "repeatEndAfter": "occurrence(s)",
        "hidden": "Hidden",
        "hourly": "Hourly",
        "daily": "Daily",
        "weekly": "Weekly",
        "monthly": "Monthly",
        "yearly": "Yearly",
        "repeatConfirm": "Do you want to edit only the current event or the whole series ?",
        "repeatConfirmLabel": "Edit Repeating Event",
        "createEvent": "Create a new Event",
        "editEvent": "Edit event",
        "editSeries": "Edit series",
        "eventException": "Event Exception",
        "collector": "more",
        "repeatEveryHour": "hours",
        "repeatEveryDay": "days",
        "repeatEveryWeek": "weeks",
        "repeatEveryMonth": "months",
        "repeatEveryYear": "years",
        "backgroundColor": "Background Color",
        "status": "Status",
        "resources": "Resources",
        "selectPlaceholder": "Select...",
        "none": "None",
        "free": "Free",
        "busy": "Busy",
        "tentative": "Tentative",
        "outOfOffice": "Out of Office",
        "exceptions": "Exceptions",
        "resetExceptions": "Reset Exceptions",
        "notifications": "Notification(s)",
        "notificationMessage": "is starting on",
        "today": "Today",
        "agendaShortcut": "A",
        "dayShortcut": "D",
        "weekShortcut": "W",
        "monthShortcut": "M",
        "timelineDayShortcut": "T+D",
        "timelineWeekShortcut": "T+W",
        "timelineMonthShortcut": "T+M",
        "showWeekends": "Show weekends",
        "beforeAt": "before at",
        "days": "days",
        "weeks": "weeks",
        "placeholder": "Add notification",
        "now": "Now",
        "dateTabLabel": "DATE",
        "timeTabLabel": "TIME",
        "hours": "Hours",
        "minutes": "Minutes",
        "am": "am",
        "pm": "pm",
        "loadingIndicatorPlaceholder": "Loading..."
      },
      de: {
        "propertyUnknownName": "Ungültiger Eigenschaftsname: '{{name}}'!",
        "propertyUnknownType": "Die Eigenschaft '{{name}}' hat keine definierte 'type'-Eigenschaft!",
        "propertyInvalidValue": "Ungültiger Wert für die Eigenschaft '{{name}}'! Tatsächlicher Wert: '{{actualValue}}', Erwarteter Wert: '{{value}}'!",
        "propertyInvalidValueType": "Ungültiger Werttyp für die Eigenschaft '{{name}}'! Tatsächlicher Typ: '{{actualType}}', Erwarteter Typ: '{{type}}'!",
        "methodInvalidValueType": "Ungültiger Wertetyp für das Argument '{{name}}' der Methode! Tatsächlicher Typ: '{{actualType}}', Erwarteter Typ: '{{type}}' für das Argument mit Index: '{{argumentIndex}}'!",
        "methodInvalidArgumentsCount": "Ungültige Anzahl an Argumenten für die Methode '{{name}}'! Tatsächliche Anzahl an Argumenten: '{{actualArgumentsCount}}', Erwartet mindestens: '{{argumentsCount}}' Argument(e)!",
        "methodInvalidReturnType": "Ungültiger Rückgabetyp für die Methode '{{name}}'! Tatsächlicher Typ: '{{actualType}}', Erwarteter Typ: '{{type}}'!",
        "elementNotInDOM": "Element existiert nicht im DOM! Bitte fügen Sie das Element dem DOM hinzu, bevor Sie eine Methode aufrufen.",
        "moduleUndefined": "Modul ist nicht definiert.",
        "missingReference": "{{elementType}}: Verweis auf '{{files}}' fehlt.",
        "htmlTemplateNotSuported": "{{elementType}}: Der Webbrowser unterstützt keine HTMLTemplate-Elemente.",
        "invalidTemplate": "{{elementType}}: Die Eigenschaft '{{property}}' akzeptiert einen String, der mit der ID eines HTMLTemplate-Elements im DOM übereinstimmen muss.",
        "invalidValue": "{{elementType}}: Ungültiger Wert für {{property}}. {{property}} sollte vom Typ {{typeOne}} oder {{typeTwo}} sein.",
        "invalidTimeZone": "{{elementType}}: Ungültiger timeZone-Wert. TimeZone sollte die ID eines zulässigen timeZone-Werts sein.",
        "incorrectArgument": "{{elementType}}: Falsches Argument {{argumentName}} in Methode {{methodName}}.",
        "noId": "smartScheduler erfordert eine ID, um einen Zustand zu speichern/laden/löschen.",
        "agenda": "Agenda",
        "agendaPlaceholder": "Keine Ereignisse zum Anzeigen",
        "day": "Tag",
        "week": "Woche",
        "month": "Monat",
        "workWeek": "Arbeitswoche",
        "allDay": "Ganztägig",
        "timelineDay": "Zeitachse Tag",
        "timelineWeek": "Zeitachse Woche",
        "timelineMonth": "Zeitachse Monat",
        "newEvent": "Neues Ereignis",
        "ok": "OK",
        "cancel": "Abbrechen",
        "delete": "Löschen",
        "label": "Beschriftung",
        "dateStart": "Startdatum",
        "dateEnd": "Enddatum",
        "repeat": "Wiederholen",
        "description": "Beschreibung",
        "repeatFreq": "Wiederholen",
        "repeatInterval": "Alle wiederholen",
        "repeatOn": "Wiederholen an",
        "repeatEnd": "Wiederholung beenden",
        "repeatEndOption": "Nie",
        "repeatEndOnOption": "Am",
        "repeatEndAfterOption": "Nach",
        "repeatEndAfter": "Vorkommen",
        "hidden": "Versteckt",
        "hourly": "Stündlich",
        "daily": "Täglich",
        "weekly": "Wöchentlich",
        "monthly": "Monatlich",
        "yearly": "Jährlich",
        "repeatConfirm": "Möchten Sie nur das aktuelle Ereignis oder die gesamte Serie bearbeiten?",
        "repeatConfirmLabel": "Wiederholendes Ereignis bearbeiten",
        "createEvent": "Neues Ereignis erstellen",
        "editEvent": "Ereignis bearbeiten",
        "editSeries": "Serie bearbeiten",
        "eventException": "Ereignis-Ausnahme",
        "collector": "mehr",
        "repeatEveryHour": "Stunden",
        "repeatEveryDay": "Tage",
        "repeatEveryWeek": "Wochen",
        "repeatEveryMonth": "Monate",
        "repeatEveryYear": "Jahre",
        "backgroundColor": "Hintergrundfarbe",
        "status": "Status",
        "resources": "Ressourcen",
        "selectPlaceholder": "Auswählen...",
        "none": "Keine",
        "free": "Frei",
        "busy": "Beschäftigt",
        "tentative": "Unsicher",
        "outOfOffice": "Abwesend",
        "exceptions": "Ausnahmen",
        "resetExceptions": "Ausnahmen zurücksetzen",
        "notifications": "Benachrichtigung(en)",
        "notificationMessage": "beginnt am",
        "today": "Heute",
        "agendaShortcut": "A",
        "dayShortcut": "T",
        "weekShortcut": "W",
        "monthShortcut": "M",
        "timelineDayShortcut": "T+T",
        "timelineWeekShortcut": "T+W",
        "timelineMonthShortcut": "T+M",
        "showWeekends": "Wochenenden anzeigen",
        "beforeAt": "vor um",
        "days": "Tage",
        "weeks": "Wochen",
        "placeholder": "Benachrichtigung hinzufügen",
        "now": "Jetzt",
        "dateTabLabel": "DATUM",
        "timeTabLabel": "ZEIT",
        "hours": "Stunden",
        "minutes": "Minuten",
        "am": "vorm.",
        "pm": "nachm.",
        "loadingIndicatorPlaceholder": "Wird geladen..."
      },
      fr: {
        "propertyUnknownName": "Nom de propriété invalide : '{{name}}' !",
        "propertyUnknownType": "La propriété '{{name}}' est définie avec un membre 'type' non défini !",
        "propertyInvalidValue": "Valeur de propriété '{{name}}' invalide ! Valeur actuelle : '{{actualValue}}', Valeur attendue : '{{value}}' !",
        "propertyInvalidValueType": "Type de valeur de propriété '{{name}}' invalide ! Type actuel : '{{actualType}}', Type attendu : '{{type}}' !",
        "methodInvalidValueType": "Type de valeur d'argument '{{name}}' de la méthode invalide ! Type actuel : '{{actualType}}', Type attendu : '{{type}}' pour l'argument d'indice : '{{argumentIndex}}' !",
        "methodInvalidArgumentsCount": "Nombre d'arguments invalide pour la méthode '{{name}}' ! Nombre d'arguments actuel : '{{actualArgumentsCount}}', Au moins '{{argumentsCount}}' argument(s) attendu(s) !",
        "methodInvalidReturnType": "Type de retour de méthode '{{name}}' invalide ! Type actuel : '{{actualType}}', Type attendu : '{{type}}' !",
        "elementNotInDOM": "L'élément n'existe pas dans le DOM ! Veuillez ajouter l'élément au DOM avant d'appeler une méthode.",
        "moduleUndefined": "Le module n'est pas défini.",
        "missingReference": "{{elementType}} : Référence manquante à '{{files}}'.",
        "htmlTemplateNotSuported": "{{elementType}} : Le navigateur Web ne prend pas en charge les éléments HTMLTemplate.",
        "invalidTemplate": "{{elementType}} : La propriété '{{property}}' accepte une chaîne qui doit correspondre à l'ID d'un élément HTMLTemplate du DOM.",
        "invalidValue": "{{elementType}} : Valeur {{property}} invalide. {{property}} doit être de type {{typeOne}} ou {{typeTwo}}.",
        "invalidTimeZone": "{{elementType}} : Valeur timeZone invalide. TimeZone doit être l'ID d'une valeur timeZone autorisée.",
        "incorrectArgument": "{{elementType}} : Argument incorrect {{argumentName}} dans la méthode {{methodName}}.",
        "noId": "smartScheduler requiert un identifiant pour sauvegarder/charger/effacer un état.",
        "agenda": "Agenda",
        "agendaPlaceholder": "Aucun événement à afficher",
        "day": "Jour",
        "week": "Semaine",
        "workWeek": "Semaine de travail",
        "month": "Mois",
        "allDay": "Toute la journée",
        "timelineDay": "Jour de la chronologie",
        "timelineWeek": "Semaine de la chronologie",
        "timelineMonth": "Mois de la chronologie",
        "newEvent": "Nouvel événement",
        "ok": "Ok",
        "cancel": "Annuler",
        "delete": "Supprimer",
        "label": "Étiquette",
        "dateStart": "Date de début",
        "dateEnd": "Date de fin",
        "repeat": "Répéter",
        "description": "Description",
        "repeatFreq": "Répéter",
        "repeatInterval": "Répéter chaque",
        "repeatOn": "Répéter le",
        "repeatEnd": "Fin de la répétition",
        "repeatEndOption": "Jamais",
        "repeatEndOnOption": "Le",
        "repeatEndAfterOption": "Après",
        "repeatEndAfter": "occurrence(s)",
        "hidden": "Masqué",
        "hourly": "Toutes les heures",
        "daily": "Quotidien",
        "weekly": "Hebdomadaire",
        "monthly": "Mensuel",
        "yearly": "Annuel",
        "repeatConfirm": "Voulez-vous modifier uniquement l'événement actuel ou toute la série ?",
        "repeatConfirmLabel": "Modifier un événement récurrent",
        "createEvent": "Créer un nouvel événement",
        "editEvent": "Modifier l'événement",
        "editSeries": "Modifier la série",
        "eventException": "Exception de l'événement",
        "collector": "plus",
        "repeatEveryHour": "heures",
        "repeatEveryDay": "jours",
        "repeatEveryWeek": "semaines",
        "repeatEveryMonth": "mois",
        "repeatEveryYear": "années",
        "backgroundColor": "Couleur de fond",
        "status": "Statut",
        "resources": "Ressources",
        "selectPlaceholder": "Sélectionner...",
        "none": "Aucun",
        "free": "Disponible",
        "busy": "Occupé",
        "tentative": "Incertain",
        "outOfOffice": "Absent",
        "exceptions": "Exceptions",
        "resetExceptions": "Réinitialiser les exceptions",
        "notifications": "Notification(s)",
        "notificationMessage": "commence le",
        "today": "Aujourd'hui",
        "agendaShortcut": "A",
        "dayShortcut": "J",
        "weekShortcut": "S",
        "monthShortcut": "M",
        "timelineDayShortcut": "T+J",
        "timelineWeekShortcut": "T+S",
        "timelineMonthShortcut": "T+M",
        "showWeekends": "Afficher les week-ends",
        "beforeAt": "avant à",
        "days": "jours",
        "weeks": "semaines",
        "placeholder": "Ajouter une notification",
        "now": "Maintenant",
        "dateTabLabel": "DATE",
        "timeTabLabel": "HEURE",
        "hours": "Heures",
        "minutes": "Minutes",
        "am": "am",
        "pm": "pm",
        "loadingIndicatorPlaceholder": "Chargement..."
      },
      es: {
        "propertyUnknownName": "Nombre de propiedad no válido: '{{name}}'!",
        "propertyUnknownType": "La propiedad '{{name}}' tiene un miembro 'type' no definido!",
        "propertyInvalidValue": "Valor de propiedad '{{name}}' no válido! Valor actual: '{{actualValue}}', Valor esperado: '{{value}}'!",
        "propertyInvalidValueType": "Tipo de valor de propiedad '{{name}}' no válido! Tipo actual: '{{actualType}}', Tipo esperado: '{{type}}'!",
        "methodInvalidValueType": "Tipo de valor de argumento '{{name}}' de método no válido! Tipo actual: '{{actualType}}', Tipo esperado: '{{type}}' para el argumento con índice: '{{argumentIndex}}'!",
        "methodInvalidArgumentsCount": "Cantidad de argumentos no válida para el método '{{name}}'! Cantidad de argumentos actual: '{{actualArgumentsCount}}', Se esperaba al menos: '{{argumentsCount}}' argumento(s)!",
        "methodInvalidReturnType": "Tipo de retorno de método '{{name}}' no válido! Tipo actual: '{{actualType}}', Tipo esperado: '{{type}}'!",
        "elementNotInDOM": "¡El elemento no existe en el DOM! Por favor, agregue el elemento al DOM antes de invocar un método.",
        "moduleUndefined": "El módulo no está definido.",
        "missingReference": "{{elementType}}: Falta referencia a '{{files}}'.",
        "htmlTemplateNotSuported": "{{elementType}}: El navegador web no admite elementos HTMLTemplate.",
        "invalidTemplate": "{{elementType}}: La propiedad '{{property}}' acepta una cadena que debe coincidir con la identificación de un elemento HTMLTemplate del DOM.",
        "invalidValue": "{{elementType}}: Valor {{property}} no válido. {{property}} debe ser de tipo {{typeOne}} o {{typeTwo}}.",
        "invalidTimeZone": "{{elementType}}: Valor de zona horaria no válido. La zona horaria debe ser la identificación de un valor de zona horaria permitido.",
        "incorrectArgument": "{{elementType}}: Argumento incorrecto {{argumentName}} en el método {{methodName}}.",
        "noId": "smartScheduler requiere un ID para guardar/cargar/borrar un estado.",
        "agenda": "Agenda",
        "agendaPlaceholder": "No hay eventos para mostrar",
        "day": "Día",
        "week": "Semana",
        "workWeek": "Semana de trabajo",
        "month": "Mes",
        "allDay": "Todo el día",
        "timelineDay": "Día de línea de tiempo",
        "timelineWeek": "Semana de línea de tiempo",
        "timelineMonth": "Mes de línea de tiempo",
        "newEvent": "Nuevo evento",
        "ok": "Aceptar",
        "cancel": "Cancelar",
        "delete": "Eliminar",
        "label": "Etiqueta",
        "dateStart": "Fecha de inicio",
        "dateEnd": "Fecha de fin",
        "repeat": "Repetir",
        "description": "Descripción",
        "repeatFreq": "Repetir",
        "repeatInterval": "Repetir cada",
        "repeatOn": "Repetir en",
        "repeatEnd": "Fin de repetición",
        "repeatEndOption": "Nunca",
        "repeatEndOnOption": "En",
        "repeatEndAfterOption": "Después de",
        "repeatEndAfter": "ocurrencia(s)",
        "hidden": "Oculto",
        "hourly": "Cada hora",
        "daily": "Diario",
        "weekly": "Semanal",
        "monthly": "Mensual",
        "yearly": "Anual",
        "repeatConfirm": "¿Desea editar solo el evento actual o toda la serie?",
        "repeatConfirmLabel": "Editar evento repetido",
        "createEvent": "Crear un nuevo evento",
        "editEvent": "Editar evento",
        "editSeries": "Editar serie",
        "eventException": "Excepción de evento",
        "collector": "más",
        "repeatEveryHour": "horas",
        "repeatEveryDay": "días",
        "repeatEveryWeek": "semanas",
        "repeatEveryMonth": "meses",
        "repeatEveryYear": "años",
        "backgroundColor": "Color de fondo",
        "status": "Estado",
        "resources": "Recursos",
        "selectPlaceholder": "Seleccionar...",
        "none": "Ninguno",
        "free": "Disponible",
        "busy": "Ocupado",
        "tentative": "Tentativo",
        "outOfOffice": "Fuera de la oficina",
        "exceptions": "Excepciones",
        "resetExceptions": "Restablecer excepciones",
        "notifications": "Notificación(es)",
        "notificationMessage": "comienza en",
        "today": "Hoy",
        "agendaShortcut": "A",
        "dayShortcut": "D",
        "weekShortcut": "S",
        "monthShortcut": "M",
        "timelineDayShortcut": "T+D",
        "timelineWeekShortcut": "T+S",
        "timelineMonthShortcut": "T+M",
        "showWeekends": "Mostrar fines de semana",
        "beforeAt": "antes a las",
        "days": "días",
        "weeks": "semanas",
        "placeholder": "Agregar notificación",
        "now": "Ahora",
        "dateTabLabel": "FECHA",
        "timeTabLabel": "HORA",
        "hours": "Horas",
        "minutes": "Minutos",
        "am": "am",
        "pm": "pm",
        "loadingIndicatorPlaceholder": "Cargando..."
      }
    }

    return messages
  }

  getProfileFormLabels(locale?: Locale): {
    firstName: string;
    lastName: string;
    emailAddress: string;
    phoneNumber: string;
    country: string;
    biography: string;
    team: string;
    saveChanges: string;
    cancel: string;
  } {
    const profileFormLabelsTranslations = {
      en: {
        firstName: 'First Name',
        lastName: 'Last Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        country: 'Country',
        team: 'Team',
        biography: 'Biography',
        saveChanges: 'Save Changes',
        cancel: 'Cancel',
      },
      de: {
        firstName: 'Vorname',
        lastName: 'Nachname',
        emailAddress: 'E-Mail-Adresse',
        phoneNumber: 'Telefonnummer',
        country: 'Land',
        team: 'Team',
        biography: 'Biografie',
        saveChanges: 'Änderungen speichern',
        cancel: 'Abbrechen',
      },
      fr: {
        firstName: 'Prénom',
        lastName: 'Nom de famille',
        emailAddress: 'Adresse e-mail',
        phoneNumber: 'Numéro de téléphone',
        country: 'Pays',
        team: 'Équipe',
        biography: 'Biographie',
        saveChanges: 'Enregistrer les modifications',
        cancel: 'Annuler',
      },
      es: {
        firstName: 'Nombre',
        lastName: 'Apellido',
        emailAddress: 'Dirección de correo electrónico',
        phoneNumber: 'Número de teléfono',
        country: 'País',
        team: 'Equipo',
        biography: 'Biografía',
        saveChanges: 'Guardar cambios',
        cancel: 'Cancelar',
      }
    };

    return profileFormLabelsTranslations[locale || this.locale];
  }
}
